### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by Kulak** [mboinet/ttrss-mobile#69]
I have not seen commits for a few years.  There are a couple thoughts in my head:

* it is done and it works well enough
* it works to some degree, but has been abandoned

**Comment by mboinet** [comment]
Hi!

Sorry no, I switched to Feedly when my daughter born. I can't find the time
to maintain this project.

But someone was interested to take this project and is co-maintainer.

**Comment by kucrut** [comment]
@Kulak You may want to try https://github.com/kucrut/ttrss-reader
@mboinet Thanks for this app, I learned a lot from it!

**Comment by Kulak** [comment]
I have tried.  I like it.
