### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by Kickball** [mboinet/ttrss-mobile#70]
Add a license to this repository.

@nodiscc

**Comment by nodiscc** [comment]
@mboinet @alexandrenorman @cy8aer @agrueneberg @stickystyle @alimony @benjaminoakes @Witti A license is indeed missing for this project. Changing license requires an agreement from all contributors.

Are you ok to license it under the AGPLv3? It is basically the GPv3 License, but requires that the sources are made available to users of the web application (not only to people running the server hosting ttrss-mobile. Basically it fixes a weakness in the GPL for web services, known as _ASP loophole_).

Another fine choice would be the MIT license.

**Comment by alimony** [comment]
I would very much prefer MIT, I'm not a big fan of GPL.

**Comment by Witti** [comment]
GPL is ok.

**Comment by mboinet** [comment]
Hi!

GPLv3 or AGLPv3 is OK for me. I'd prefer to avoid MIT but it doesn't really matter.

**Comment by nodiscc** [comment]
I'd also prefer to avoid MIT (I believe the user of the web service _must_ be informed of the Free Software nature of the service he/she's using, and that the service should at least _point_ to the source. AGPL solves this.), but feel free to propose the license you want, and we can sort this out later.

Thanks for your replies everyone, waiting to hear from @alexandrenorman @agrueneberg @stickystyle @benjaminoakes  @cy8aer

**Comment by agrueneberg** [comment]
I believe @mboinet has more say in this than me. AGPLv3 it is.

**Comment by benjaminoakes** [comment]
GPLv3 or AGPLv3 is fine by me

**Comment by cy8aer** [comment]
GPLv3 or AGPLv3 would be fine for me too

**Comment by cy8aer** [comment]
more AGPL than GPL (sorry)

**Comment by alimony** [comment]
However, you can count me as agreeing on GPL too, it seems to be leaning that way and I don't feel that strongly about it.

**Comment by Kickball** [comment]
How long do we plan on waiting for @alexandrenorman and @stickystyle?

**Comment by stickystyle** [comment]
Sorry, totally missed this ticket. AGPL is fine by me.

**Comment by alexandrenorman** [comment]
Hello,

Sorry, I don't mind. I switched to other projects and do not use ttrss
anymore :-/

Regards,
Alexandre

**Comment by nodiscc** [comment]
Thanks everyone! ttrss-mobile is now under the AGPLv3 license, the license text has been added in LICENSE, and a link to this file added in the README.
